version: "{build}"

configuration: Release

image:
  - Visual Studio 2015
  - Visual Studio 2017

before_build:
  # 
  
build_script:
  # build
  - mkdir %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config %CONFIGURATION% 

test_script:
  # run test
  - cd %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%
  - Osiris.exe ../../data
  